name: Netlify Build on Tag or Blog Changes

on:
  push:
    paths:
      - '*'
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Netlify Webhook
        run: echo ".md file has been changed!"
